/**
 * Reads .env (and Vercel/CI env vars) and generates src/environments/env.secrets.ts
 * Run automatically before start/build via package.json prestart/prebuild.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'src/environments/env.secrets.ts');

function parseEnv(content) {
  const result = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    let val = trimmed.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    result[key] = val.replace(/\r$/, '').trim();
  }
  return result;
}

let vars = {};
if (fs.existsSync(envPath)) {
  vars = parseEnv(fs.readFileSync(envPath, 'utf8'));
} else {
  console.warn('[sync-env] No .env file found — copy .env.example to .env and add your keys.');
}

if (process.env.OPENROUTER_API_KEY) {
  vars.OPENROUTER_API_KEY = String(process.env.OPENROUTER_API_KEY).trim();
}
if (process.env.OPENROUTER_MODEL) {
  vars.OPENROUTER_MODEL = String(process.env.OPENROUTER_MODEL).trim();
}

const apiKey = (vars.OPENROUTER_API_KEY || '').trim();
const model = (vars.OPENROUTER_MODEL || 'meta-llama/llama-3.1-8b-instruct').trim();
const onVercel = !!(process.env.VERCEL || process.env.VERCEL_ENV);

const content = `// AUTO-GENERATED by scripts/sync-env.js — do not edit or commit
export const envSecrets = {
  openRouterApiKey: ${JSON.stringify(apiKey)},
  openRouterModel: ${JSON.stringify(model)},
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
if (apiKey) {
  const source = process.env.OPENROUTER_API_KEY ? 'Vercel/CI env' : '.env file';
  console.log(`[sync-env] OPENROUTER_API_KEY loaded from ${source}`);
} else if (onVercel) {
  console.warn('[sync-env] WARNING: OPENROUTER_API_KEY missing on Vercel build!');
  console.warn('[sync-env] Add OPENROUTER_API_KEY in Vercel → Settings → Environment Variables → Redeploy');
} else {
  console.warn('[sync-env] No OPENROUTER_API_KEY — copy .env.example to .env for local Barangay AI');
}
